# Generated by Django 3.2.5 on 2021-08-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20210819_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_user',
            options={'verbose_name': 'User Login Detail'},
        ),
        migrations.AlterModelTable(
            name='contact_user',
            table='blog_app_sign_up',
        ),
    ]
