# Generated by Django 3.2.5 on 2021-08-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_contact_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_user',
            old_name='password',
            new_name='comments',
        ),
    ]
