# Generated by Django 3.2.5 on 2021-08-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_rename_password_contact_user_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_user',
            options={'verbose_name': 'User commants Detail'},
        ),
        migrations.AlterField(
            model_name='contact_user',
            name='comments',
            field=models.TextField(max_length=200),
        ),
    ]
