# Generated by Django 3.2.5 on 2021-08-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20210819_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_user',
            name='subject',
            field=models.CharField(default='No subject', max_length=200),
        ),
    ]
