# Generated by Django 3.2.5 on 2021-08-20 04:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_contact_user_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('slug', models.CharField(max_length=50)),
                ('thambnil', models.ImageField(upload_to='images')),
                ('blog', models.TextField()),
                ('date', models.DateField(verbose_name=datetime.datetime(2021, 8, 20, 9, 38, 25, 210405))),
                ('time', models.TimeField(verbose_name=datetime.datetime(2021, 8, 20, 4, 8, 25, 210405, tzinfo=utc))),
            ],
        ),
    ]
