# Generated by Django 3.2.5 on 2021-08-20 04:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_auto_20210820_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 20, 9, 52, 3, 251869)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 8, 20, 4, 22, 3, 251869, tzinfo=utc)),
        ),
    ]
