# Generated by Django 3.2.5 on 2021-08-20 05:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_auto_20210820_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_page_img',
            field=models.ImageField(default="{%static 'images/logo.png'%}", upload_to='images'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
