# Generated by Django 3.2.6 on 2021-08-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_auto_20210820_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_page_img',
            field=models.ImageField(default='images/blog_1.png', upload_to='images'),
        ),
    ]
